# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "12:00"
      timezone: "Etc/UTC"
    commit-message:
      # Prefix all commit messages with "chore: "
      prefix: "chore"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 6
    # Raise pull requests for version updates
    # to pip against the `dev` branch
    target-branch: "staging"
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot/npm_and_yarn-next_js-acorn-6.4.1`
      separator: "/"
    # Update the npm manifest file to relax
    # the version requirements
    versioning-strategy: increase-if-necessary
    # Add assignees
    assignees:
      - "princemuel"
