tailwindConfig: "tailwind.config.js"
tailwindFunctions:
  - tw
  - cn
  - tv
tailwindAttributes:
  - tw

astroAllowShorthand: false
plugins:
  - prettier-plugin-astro
  - prettier-plugin-organize-imports
  - prettier-plugin-prisma
  - prettier-plugin-tailwindcss

overrides:
  - files: "*.astro"
    options:
      parser: "astro"
      printWidth: 80
      tabWidth: 2
      useTabs: false
      semi: true
      singleQuote: false
      quoteProps: "as-needed"
      jsxSingleQuote: false
      trailingComma: "all"
      bracketSpacing: true
      bracketSameLine: false
      arrowParens: "always"
      experimentalTernaries: false
