settings:
  bullet: "*"
  listItemIndent: "one"
plugins:
  - remark-frontmatter
  - remark-preset-lint-consistent
  - remark-preset-lint-markdown-style-guide
  - remark-preset-lint-recommended
  - preset-prettier
